# PlatformIO pre-build script: gzip web/index.html into include/generated/web_assets.h (PROGMEM byte array).
# Only rewrites the header when the page content changed, so incremental builds stay fast.
Import("env")
import gzip, hashlib, pathlib, re

root = pathlib.Path(env["PROJECT_DIR"])
src = root / "web" / "index.html"
out = root / "include" / "generated" / "web_assets.h"

raw = src.read_bytes()
raw = re.sub(rb"<!--.*?-->", b"", raw, flags=re.S)          # strip HTML comments
gz = gzip.compress(raw, compresslevel=9, mtime=0)             # mtime=0 -> reproducible bytes
etag = hashlib.sha1(gz).hexdigest()[:12]

if out.exists() and etag.encode() in out.read_bytes():
    print(f"build_web: web_assets.h up to date ({len(gz)} bytes gzipped)")
else:
    lines = []
    for i in range(0, len(gz), 16):
        lines.append(", ".join(f"0x{b:02x}" for b in gz[i:i + 16]))
    body = ",\n  ".join(lines)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// Generated by tools/build_web.py - do not edit\n"
        "#pragma once\n#include <pgmspace.h>\n#include <stddef.h>\n#include <stdint.h>\n"
        f"static const char WEB_INDEX_ETAG[] = \"\\\"{etag}\\\"\";\n"
        f"static const size_t WEB_INDEX_GZ_LEN = {len(gz)};\n"
        f"static const uint8_t WEB_INDEX_GZ[] PROGMEM = {{\n  {body}\n}};\n"
    )
    print(f"build_web: wrote web_assets.h ({len(raw)} -> {len(gz)} bytes)")
