# PlatformIO pre-build script: packs the web UI into include/generated/web_assets.h.
#   web/index.html, web/setup.html  -> gzipped PROGMEM arrays (WEB_INDEX_*, WEB_SETUP_*)
#   web/manifest.webmanifest, web/sw.js -> plain PROGMEM strings
#   app icons (192/512 px PNG) -> drawn here with a tiny PNG encoder, no image library needed
# Only rewrites the header when an input changed, so incremental builds stay fast.
Import("env")
import gzip, hashlib, pathlib, re, struct, zlib

root = pathlib.Path(env["PROJECT_DIR"])
web = root / "web"
out = root / "include" / "generated" / "web_assets.h"
SCRIPT_VERSION = "3"

# ---- icon drawing: a slice of the clock face rendered as LED dots ----------------------------------------
DIGITS = {  # 7x11 clock digits, bit 6 = leftmost column (same as include/fonts/digits_7x11.h)
    '7': [0x7F,0x03,0x03,0x06,0x06,0x0C,0x0C,0x18,0x18,0x18,0x18], '4': [0x06,0x0E,0x1E,0x36,0x66,0x66,0x7F,0x06,0x06,0x06,0x06],
    '1': [0x0C,0x1C,0x3C,0x0C,0x0C,0x0C,0x0C,0x0C,0x0C,0x0C,0x3F], ':': [0,0,0,0x18,0x18,0,0,0x18,0x18,0,0],
}
GLCD = {'7': [65,33,17,9,7], '2': [114,73,73,73,70], 'F': [127,9,9,9,1], '\xb0': [6,15,9,15,6]}   # 5x7 columns, bit 0 = top

def led_frame():
    """Returns a dict {(col,row): (r,g,b)} for a 42x32 slice of the clock: 7:41 on top, sun + 72°F below."""
    px = {}
    def put(x, y, c): px[(x, y)] = c
    WHITE, AMBER, SUN = (255, 255, 255), (255, 208, 96), (255, 204, 0)
    x0, y0 = 3, 6
    for ch, cx in (('7', 0), (':', 16), ('4', 21), ('1', 29)):
        for r, bits in enumerate(DIGITS[ch]):
            for col in range(7):
                if bits & (0x40 >> col): put(x0 + cx + col, y0 + r, WHITE)
    # sun: disc radius 3 + rays, centred at (8, 28)
    cx, cy = 8, 28
    for x in range(cx - 3, cx + 4):
        for y in range(cy - 3, cy + 4):
            if (x - cx) ** 2 + (y - cy) ** 2 <= 9.5: put(x, y, SUN)
    for dx, dy in ((-6, 0), (-5, 0), (5, 0), (6, 0), (0, -6), (0, -5), (0, 5), (0, 6), (-4, -4), (4, -4), (-4, 4), (4, 4)):
        put(cx + dx, cy + dy, SUN)
    tx = 18
    for ch in "72\xb0F":
        for i, colbits in enumerate(GLCD[ch]):
            for j in range(8):
                if colbits & (1 << j): put(tx + i, 25 + j, AMBER)
        tx += 6
    return px

def png_bytes(size):
    cols, rows, pitch = 42, 32, size / 42.0
    top = (size - rows * pitch) / 2
    frame = led_frame()
    bg, off = (14, 17, 22), (31, 35, 42)
    r2 = (pitch * 0.42) ** 2
    raw = bytearray()
    for py in range(size):
        raw.append(0)   # filter: none
        row = int((py - top) // pitch)
        for pxx in range(size):
            col = int(pxx // pitch)
            colour = bg
            if 0 <= row < rows and 0 <= col < cols:
                dx = pxx - (col * pitch + pitch / 2) + 0.5
                dy = py - (top + row * pitch + pitch / 2) + 0.5
                if dx * dx + dy * dy <= r2:
                    colour = frame.get((col, row), off)
            raw += bytes(colour)
    def chunk(tag, data):
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    ihdr = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b"")

def c_array(name, data):
    lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    return f"static const size_t {name}_LEN = {len(data)};\nstatic const uint8_t {name}[] PROGMEM = {{\n  " + ",\n  ".join(lines) + "\n};\n"

def c_string(name, text):
    esc = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'static const char {name}[] PROGMEM = "{esc}";\n'

inputs = {p.name: p.read_bytes() for p in sorted(web.iterdir()) if p.is_file()}
digest = hashlib.sha1(SCRIPT_VERSION.encode() + b"".join(n.encode() + v for n, v in inputs.items())).hexdigest()[:12]
if out.exists() and digest.encode() in out.read_bytes():
    print("build_web: web_assets.h up to date")
else:
    parts = ["// Generated by tools/build_web.py - do not edit\n#pragma once\n#include <pgmspace.h>\n#include <stddef.h>\n#include <stdint.h>\n",
             f'static const char WEB_ASSETS_DIGEST[] = "{digest}";\n']
    for page in ("index", "setup"):
        raw = re.sub(rb"<!--.*?-->", b"", inputs[f"{page}.html"], flags=re.S)
        gz = gzip.compress(raw, compresslevel=9, mtime=0)
        etag = hashlib.sha1(gz).hexdigest()[:12]
        up = page.upper()
        parts.append(f'static const char WEB_{up}_ETAG[] = "\\"{etag}\\"";\n' + c_array(f"WEB_{up}_GZ", gz).replace(f"WEB_{up}_GZ_LEN", f"WEB_{up}_GZ_LEN"))
        print(f"build_web: {page}.html {len(raw)} -> {len(gz)} bytes")
    parts.append(c_string("WEB_MANIFEST", inputs["manifest.webmanifest"].decode()))
    parts.append(c_string("WEB_SW_JS", inputs["sw.js"].decode()))
    for size in (192, 512):
        data = png_bytes(size)
        parts.append(c_array(f"WEB_ICON_{size}", data))
        print(f"build_web: icon {size}px {len(data)} bytes")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(parts))
    print("build_web: wrote web_assets.h")
